name = "finvault-dashboard"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"


# Serve the built React files
# [site]
# bucket = "./dist"
# entry-point = "workers-site"


# We will add D1 configuration here later
[[d1_databases]]
binding = "DB"
database_name = "finvault-db"
database_id = "9c088e26-7053-41e9-9e43-03ea9fd36f9a"

